---
title: "example_workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
  
  library(tidyverse)
  library(envImport)

  out_dir <- here::here("inst", "out", "ds") # ds for data source

```

```{r aoi}

  aoi <- sf::st_read(here::here("inst", "shp", "Bakara_smaller.shp"))

  aoi_buffer <- aoi %>%
    sf::st_buffer(50000) %>%
    sf::st_transform(crs = 4283) %>%
    sf::st_make_valid()

```

```{r gbif}

  gbif_dir <- here::here(out_dir, "gbif")

  gbif_raw <- get_gbif(aoi = aoi_buffer
                       , save_dir = gbif_dir
                       , get_new = FALSE
                       , rgbif::pred_gte("year", 2022)
                       )

  gbif <- make_gbif(gbif_raw
                    , data_map = envImport::data_map
                    )

```

```{r tern}

  tern_dir <- here::here(out_dir, "tern")

  tern_raw <- get_tern(aoi = aoi_buffer
                       , save_dir = tern_dir
                       , get_new = FALSE # while testing
                       , veg.PI = TRUE
                       )

  tern <- make_tern(tern_raw
                    , data_map = data_map
                    )

```

```{r assemble}

  bio_all <- unite_data(data_map
                      , get_new = TRUE
                      , out_file = here::here("inst", "out", "ds", "bio_all.parquet")
                      )

```
