

#' Summarise raster files
#'
#' Rasters are stacked via [terra::rast()], then summaries are generated by
#' [terra::app()]. Summaries are saved to file.
#'
#' @param paths Character. Paths to any raster that can be read by
#' [terra::rast()].
#' @param out_base Character. Path including start of file name. Appended with
#' `_func.tif`.
#' @param force_new Logical. Run summarise even if resulting file already
#' exists.
#' @param funcs List of functions to use in summarising rasters.
#' @param out_type Extension for raster file written. Required as filename is
#' created from `out_base` and `func` so can't be passed directly.
#' @param ... Passed to [terra::app()]. Thus, (presumably) includes options to
#' [terra::writeRaster()] via `wopt` argument (untested).
#'
#' @return Side effect of saving summarised raster(s).
#' @export
#'
#' @examples
summarise_rast_paths <- function(paths
                                , out_base = tempfile()
                                , force_new = FALSE
                                , funcs = list(mean = mean
                                               , med = median
                                               , min = min
                                               , max = max
                                               , sd = sd
                                               )
                                , out_type = "tif"
                                , ...
                                ) {

  s <- terra::rast(as.character(paths))

  summarise_func <- function(func, func_name) {

    out_file <- paste0(out_base
                       , "_"
                       , func_name
                       , "."
                       , out_type
                       )

    do <- !file.exists(out_file)

    if(force_new) do <- TRUE

    if(do) {

      terra::app(s
                 , fun = func
                 , filename = out_file
                 , ...
                 )

    }

  }

  purrr::walk2(funcs
               , names(funcs)
               , summarise_func
               )

}
