

#' Summarise raster files
#'
#' Rasters are stacked via [terra::rast()], then summaries are generated by
#' [terra::app()]. Summaries are saved to file. Rasters are split
#' by index (using [terra::subset()]) before summarising, allowing for
#' multi-layer rasters. Lyr`n` is added to filename.
#'
#' @param paths Character. Paths to any raster that can be read by
#' [terra::rast()].
#' @param out_base Character. Path including start of file name. Appended with
#' `_func.tif`.
#' @param force_new Logical. Run summarise even if resulting file already
#' exists.
#' @param funcs Function to apply to each vector of stacked cells.
#' @param out_type Extension for raster file written. Required as filename is
#' created from `out_base` and `func` so can't be passed directly.
#' @param ... Passed to [terra::app()]. Thus, (presumably) includes options to
#' [terra::writeRaster()] via `wopt` argument (untested).
#'
#' @return Side effect of saving summarised raster(s) to file.
#' @export
#'
#' @examples
#'
#'
summarise_rast_paths <- function(paths
                                 , out_base = tempfile()
                                 , force_new = FALSE
                                 , funcs = c("mean", "median", "min", "max", "sd")
                                 , out_type = "tif"
                                 , ...
                                 ) {

  fs::dir_create(dirname(out_base))

  s <- terra::rast(as.character(paths))

  layers <- names(terra::rast(paths[[1]]))

  stacks <- tibble::tibble(layer = layers) %>%
    dplyr::mutate(layer_id = dplyr::row_number()
                  , subsets = purrr::map(layer_id, ~ seq(., length(layers)* length(paths), by = length(layers)))
                  , s = purrr::map(subsets
                                   , ~terra::subset(s
                                                    , .
                                                    )
                                   )
                  ) %>%
    dplyr::left_join(tibble::tibble(func = funcs)
                     , by = character()
                     )

  summarise_func <- function(lyr_stack, layer_id, func_name) {

    out_file <- paste0(out_base
                       , "_"
                       , func_name
                       , "_lyr"
                       , layer_id
                       , "."
                       , out_type
                       )

    do <- !file.exists(out_file)

    if(force_new) do <- TRUE

    if(do) {

      terra::app(lyr_stack
                 , fun = get(func_name)
                 , filename = out_file
                 , ...
                 )

    }

  }

  purrr::pwalk(list(stacks$s
                    , stacks$layer_id
                    , stacks$func
                    )
               , summarise_func
               )

}

